config/routes.rb
Rails.application.routes.draw do
  # get 'items/create'
  devise_for :users

  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end

  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :name, length: {minimum: 1}, presence: true

  default_scope { order(created_at: :desc) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items, dependent: :destroy

  # adding name validations
  validates :name, length: { minimum: 1, maximum: 20 }, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :authenticate_user!, :except => [:index, :show]
  # allow name attribute
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def create
    @items = current_user.items.build(params[:name])
    @items.name = params[:items][:name]

    if @items.save
      flash[:notice] = "Item saved to your To-Do list"
      redirect_to root_path
    else
      flash[:alert] = "Hmmm...something when wrong, try again"
      redirect_to root_path
    end

  end

  def destroy
    @items = Item.find(params[:id])
    @items.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Item Completed" }
      format.js {flash.now[:notice] = "Item Completed"}
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id] || current_user.id)
    @user.items = current_user.items
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    # => used to build the html and css to dosplay the form element and any associated errors
    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="form-group new-item-form">
  <%= form_for :items, url: user_items_path(user_id: @user.id), method: :post, remote: true do |f| %>
      <%= f.submit "Add", class: "btn btn-default submit-btn-sign-up add-item-btn"%>
      <div class="inline-form">
        <%= f.text_field :name, class: "form-control add-item", autofocus: true, placeholder: "Enter new To-Do item"%>
      </div>
  <% end %>
</div>

app/views/items/_item.html.erb
    <div id="item-list" class="field">
        <% @user.items.each do |item| %>
        <ul class="list">
          <li class="to-do-list-items"><div class="item-name"><%= item.name %></div>
            <span id="remove">
              <%= link_to "", user_item_path(user_id: @user.id, id: item.id), method: :delete, class: 'complete-icon glyphicon glyphicon-ok', title:"mark item as complete", remote: true %>
            </span>
            <small class="time-ago">created <%= distance_of_time_in_words(Time.now, item.created_at) %> ago</small>
          </li>
        </ul>
        <% end %>
    </div>

app/views/items/create.js.erb
// $('.to-do-list').append("<%= escape_javascript(render partial: 'item', locals: {user: @user}%>")

app/views/items/destroy.js.erb
// ajax request to delete item
$('.complete-icon').bind('ajax:success', function() { 
   $(this).closest('li').fadeOut("slow", "swing", function() { //speed, style, callback after ajax
     var count = <%= current_user.items.count %>;
     $('.to-do-count').html(count--); //callback to change the current_user.item.count
   });
});

// flash alert after ajax request
<% flash.each do |type, message| %>
  $("#flash_messages_partial").html('<div class="alert alert-warning"><button type="button" class="close" data-dismiss="alert">&times;</button><%= flash[:notice] %></div>')
<% end %>

app/views/layouts/_flash_msg.html.erb
<div id="flash_messages_partial">
  <% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
   <% elsif flash.now[:alert] %>
     <div class="alert alert-danger">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash.now[:alert] %>
     </div>
   <% elsif flash[:alert] %>
     <div class="alert alert-warning">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:alert] %>
     </div>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%><!--, 'data-turbolinks-track': 'reload' %> -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
    <%= javascript_include_tag 'application'%> <!--, 'data-turbolinks-track': 'reload' %>-->
  </head>

  <body>
    <nav class="navbar">
      <div><%= link_to "Blocitoff", root_path, class: "pull-left title" %></div>
      <div class="pull-right nav-user-info">
        <% if user_signed_in? %>
         <strong><%= current_user.name %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link nav-user-info' %>- <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link nav-user-info'  %>
     <% else %>
       <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link nav-user-info'  %>
       <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link nav-user-info'  %>
     <% end %>
     </div>
   </nav>

   <%= render partial: "layouts/flash_msg" %>

 <%= yield %>

  </body>
</html>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <h1 class="user-prof-name">
      <%=@user.name.capitalize%>
      <small class="pull-right">To-Do's: <span class="to-do-count"><%=@user.items.count %></span></small>
    </h1>
    <div class="pull-left about-info">
      <p class="about-text">Create To-Do items <span class="glyphicon glyphicon-arrow-right"> </span></br>
      Items will be deleted after 7 days</br>
      Mark items complete by clicking the <span class='complete-icon glyphicon glyphicon-ok'></span></p>
    </div>
  </div>
  <div class="text-center">
    </br>
    <div class="to-do-list col-md-6 col-md-offset-3">
      <%= render partial: "items/form", locals: {user: @user} %>
      <%= render partial: "items/item", locals: {user: @user} %>
    </div>
  </div>
</div>

</div>

app/views/welcome/index.html.erb
<div class="text-center center-login">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="thumbnail index-login">
        <div class="caption">
          <h3>Welcome to Bloccitoff</h3>
          <p>You have 7 days to complete a task </br> or it disappears</p

          <p>
            <%= link_to "Sign In", new_user_session_path, :class =>"btn btn-default submit-btn-sign-up" %>
            <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-default submit-btn-sign-up index-btn"%>
        </div>
      </div>
    </div>
  </div>
</div>